### ISSUE TITLE
Icons for the Divider of Learn Page

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage4/grad.then#184]
Change 3 "placeholder" **SVG** icons to the `Divider` of learn page to meaningful icons.
Icon meaning / Text under the icon:
- courses / number of courses, number of courses starting this month, week, today...
- interview questions / number of questions, preferably a **BIG** number
- time, timer, clock / number of hours in a day needed to became a **hireable web dev** in 3 month :grin: 

ready to accept other **fun** icons (meaning, content) and texts. :upside_down_face:

**Comment by mar-bi** [comment]
Welcome to vote! :upside_down_face: 

![image](https://user-images.githubusercontent.com/25195616/34917449-61d4e6ba-f94f-11e7-928e-014e7e237b69.png)

**Comment by spences10** [comment]
Icon display
Icon-bubbles4

I'm not sure on the context for Time? 🤔 

If it is for something that is running out then the first two or if it is for specific times then the second two?

**Comment by mar-bi** [comment]
I'm thinking about the meaning of the Time icon.
Can it be:
- an average course duration, 
- how long it takes to finish all the courses,
- number of hours in a day needed to became a hire-able web dev in 3 month,
- something else...:question:

**Comment by mar-bi** [comment]
**Another idea** - instead of time (which has a vague meaning in the current context) let's count course providers (authors, institutions, etc) :school: 

![image](https://user-images.githubusercontent.com/25195616/35265896-2b597376-002a-11e8-8c0c-dccbeb3d4f9b.png)

P.S. Personally, I prefer the **first** icon (icon-library) :upside_down_face:
